Added TIFF export in the save dialog.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -465,7 +465,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS SET_MAKE LN_S RM TOUCH MKDIR INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL OPTS PKG_CONFIG PKG_CONFIG_PATH X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS QTDIR QMAKE MOC UIC RCC LUPDATE LRELEASE DDJVUAPI_LIBS DDJVUAPI_CFLAGS NSDEJAVU_CFLAGS NSDEJAVU_LIBS INSTALL_SHLIB XDG_MIME XDG_ICON_RESOURCE XDG_DESKTOP_MENU LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS SET_MAKE LN_S RM TOUCH MKDIR INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL OPTS PKG_CONFIG PKG_CONFIG_PATH X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS QTDIR QMAKE MOC UIC RCC LUPDATE LRELEASE DDJVUAPI_LIBS DDJVUAPI_CFLAGS TIFF_LIBS TIFF_CFLAGS NSDEJAVU_CFLAGS NSDEJAVU_LIBS INSTALL_SHLIB XDG_MIME XDG_ICON_RESOURCE XDG_DESKTOP_MENU LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -990,6 +990,14 @@ ac_env_DDJVUAPI_CFLAGS_set=${DDJVUAPI_CFLAGS+set}
 ac_env_DDJVUAPI_CFLAGS_value=$DDJVUAPI_CFLAGS
 ac_cv_env_DDJVUAPI_CFLAGS_set=${DDJVUAPI_CFLAGS+set}
 ac_cv_env_DDJVUAPI_CFLAGS_value=$DDJVUAPI_CFLAGS
+ac_env_TIFF_LIBS_set=${TIFF_LIBS+set}
+ac_env_TIFF_LIBS_value=$TIFF_LIBS
+ac_cv_env_TIFF_LIBS_set=${TIFF_LIBS+set}
+ac_cv_env_TIFF_LIBS_value=$TIFF_LIBS
+ac_env_TIFF_CFLAGS_set=${TIFF_CFLAGS+set}
+ac_env_TIFF_CFLAGS_value=$TIFF_CFLAGS
+ac_cv_env_TIFF_CFLAGS_set=${TIFF_CFLAGS+set}
+ac_cv_env_TIFF_CFLAGS_value=$TIFF_CFLAGS
 
 #
 # Report the --help message.
@@ -1092,6 +1100,7 @@ Optional Packages:
   --with-tags[=TAGS]
                           include additional configurations [automatic]
   --with-x                use the X Window System
+  --with-tiff=DIR         where libtiff is located
 
 Some influential environment variables:
   CC          C compiler command
@@ -1120,6 +1129,8 @@ Some influential environment variables:
               Libraries for ddjvuapi
   DDJVUAPI_CFLAGS
               Compilation flags for ddjvuapi
+  TIFF_LIBS   Libraries for tiff
+  TIFF_CFLAGS Compilation flags for tiff
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -3767,7 +3778,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3770 "configure"' > conftest.$ac_ext
+  echo '#line 3781 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4878,7 +4889,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:4881:" \
+echo "$as_me:4892:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -5978,11 +5989,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:5981: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:5992: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:5985: \$? = $ac_status" >&5
+   echo "$as_me:5996: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6240,11 +6251,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6243: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6254: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6247: \$? = $ac_status" >&5
+   echo "$as_me:6258: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6302,11 +6313,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6305: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6316: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6309: \$? = $ac_status" >&5
+   echo "$as_me:6320: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8554,7 +8565,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8557 "configure"
+#line 8568 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8652,7 +8663,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8655 "configure"
+#line 8666 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10909,11 +10920,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10912: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10923: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10916: \$? = $ac_status" >&5
+   echo "$as_me:10927: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -10971,11 +10982,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10974: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10985: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10978: \$? = $ac_status" >&5
+   echo "$as_me:10989: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12356,7 +12367,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12359 "configure"
+#line 12370 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12454,7 +12465,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12457 "configure"
+#line 12468 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13339,11 +13350,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13342: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13353: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13346: \$? = $ac_status" >&5
+   echo "$as_me:13357: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13401,11 +13412,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13404: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13415: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13408: \$? = $ac_status" >&5
+   echo "$as_me:13419: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15546,11 +15557,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15549: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15560: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15553: \$? = $ac_status" >&5
+   echo "$as_me:15564: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15808,11 +15819,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15811: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15822: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15815: \$? = $ac_status" >&5
+   echo "$as_me:15826: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15870,11 +15881,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15873: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15884: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15877: \$? = $ac_status" >&5
+   echo "$as_me:15888: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18122,7 +18133,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18125 "configure"
+#line 18136 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18220,7 +18231,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18223 "configure"
+#line 18234 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -22900,6 +22911,115 @@ echo "$as_me: error: Cannot find required package ddjvuapi." >&2;}
 
 
 
+
+  ac_tiff=no
+
+# Check whether --with-tiff or --without-tiff was given.
+if test "${with_tiff+set}" = set; then
+  withval="$with_tiff"
+  ac_tiff=$withval
+else
+  ac_tiff=yes
+fi;
+  # Process specification
+  if test x$ac_tiff = xyes ; then
+     test x${TIFF_LIBS+set} != xset && TIFF_LIBS="-ltiff"
+  elif test x$ac_tiff != xno ; then
+     test x${TIFF_LIBS+set} != xset && TIFF_LIBS="-L$ac_tiff/lib -ltiff"
+     test x${TIFF_CFLAGS+set} != xset && TIFF_CFLAGS="-I$ac_tiff/include"
+  fi
+  # Try linking
+  if test x$ac_tiff != xno ; then
+     echo "$as_me:$LINENO: checking for the libtiff library" >&5
+echo $ECHO_N "checking for the libtiff library... $ECHO_C" >&6
+     save_CFLAGS="$CFLAGS"
+     save_CXXFLAGS="$CXXFLAGS"
+     save_LIBS="$LIBS"
+     CFLAGS="$CFLAGS $TIFF_CFLAGS"
+     CXXFLAGS="$CXXFLAGS $TIFF_CFLAGS"
+     LIBS="$LIBS $TIFF_LIBS"
+     cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#ifdef __cplusplus
+extern "C" {
+#endif
+#include <stdio.h>
+#include <tiffio.h>
+#ifdef __cplusplus
+}
+#endif
+int
+main ()
+{
+
+TIFFOpen(0,0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_tiff=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_tiff=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+     CFLAGS="$save_CFLAGS"
+     CXXFLAGS="$save_CXXFLAGS"
+     LIBS="$save_LIBS"
+     echo "$as_me:$LINENO: result: $ac_tiff" >&5
+echo "${ECHO_T}$ac_tiff" >&6
+   fi
+   # Finish
+   if test x$ac_tiff = xno; then
+      TIFF_CFLAGS= ; TIFF_LIBS=
+
+  { echo "$as_me:$LINENO: WARNING: Cannot find libtiff (required for tiff export)." >&5
+echo "$as_me: WARNING: Cannot find libtiff (required for tiff export)." >&2;}
+
+   else
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TIFF 1
+_ACEOF
+
+      echo "$as_me:$LINENO: result: setting TIFF_CFLAGS=$TIFF_CFLAGS" >&5
+echo "${ECHO_T}setting TIFF_CFLAGS=$TIFF_CFLAGS" >&6
+      echo "$as_me:$LINENO: result: setting TIFF_LIBS=$TIFF_LIBS" >&5
+echo "${ECHO_T}setting TIFF_LIBS=$TIFF_LIBS" >&6
+      :
+   fi
+
+
+
 # ----------------------------------------
 # How to compile and install nsdejavu
 # ----------------------------------------
@@ -24821,7 +24941,7 @@ QARG="$QARG QMAKE_CXXFLAGS+="'"'"$CXXFLAGS $AUTO_FLAGS"'"'
 # is now useless because we set QMAKE_COMMAND with read!
 
 # run
-          ac_config_commands="$ac_config_commands src/Makefile"
+                    ac_config_commands="$ac_config_commands src directory"
 
 
 
@@ -25377,7 +25497,8 @@ do
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "nsdejavu/Makefile" ) CONFIG_FILES="$CONFIG_FILES nsdejavu/Makefile" ;;
   "desktopfiles/Makefile" ) CONFIG_FILES="$CONFIG_FILES desktopfiles/Makefile" ;;
-  "src/Makefile" ) CONFIG_COMMANDS="$CONFIG_COMMANDS src/Makefile" ;;
+  "src" ) CONFIG_COMMANDS="$CONFIG_COMMANDS src" ;;
+  "directory" ) CONFIG_COMMANDS="$CONFIG_COMMANDS directory" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h:config/config.h.in" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
@@ -25520,6 +25641,8 @@ s,@LUPDATE@,$LUPDATE,;t t
 s,@LRELEASE@,$LRELEASE,;t t
 s,@DDJVUAPI_LIBS@,$DDJVUAPI_LIBS,;t t
 s,@DDJVUAPI_CFLAGS@,$DDJVUAPI_CFLAGS,;t t
+s,@TIFF_LIBS@,$TIFF_LIBS,;t t
+s,@TIFF_CFLAGS@,$TIFF_CFLAGS,;t t
 s,@NSDEJAVU_CFLAGS@,$NSDEJAVU_CFLAGS,;t t
 s,@NSDEJAVU_LIBS@,$NSDEJAVU_LIBS,;t t
 s,@INSTALL_SHLIB@,$INSTALL_SHLIB,;t t
@@ -26104,8 +26227,12 @@ esac
   { echo "$as_me:$LINENO: executing $ac_dest commands" >&5
 echo "$as_me: executing $ac_dest commands" >&6;}
   case $ac_dest in
-    src/Makefile )
-     echo "config.status: running $qmake_QMAKE in directory src."
+    src )
+     echo "config.status: running $QMAKE_COMMAND."
+     ( cd src ; eval "$QMAKE_COMMAND" )
+ ;;
+    directory )
+     echo "config.status: running $QMAKE_COMMAND."
      ( cd src ; eval "$QMAKE_COMMAND" )
  ;;
   esac
