forgot xdg in configure.ac

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -465,7 +465,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS SET_MAKE LN_S RM TOUCH MKDIR INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL OPTS PKG_CONFIG PKG_CONFIG_PATH X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS QTDIR QMAKE MOC UIC RCC LUPDATE LRELEASE DDJVUAPI_LIBS DDJVUAPI_CFLAGS NSDEJAVU_CFLAGS NSDEJAVU_LIBS INSTALL_SHLIB LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS SET_MAKE LN_S RM TOUCH MKDIR INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL OPTS PKG_CONFIG PKG_CONFIG_PATH X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS QTDIR QMAKE MOC UIC RCC LUPDATE LRELEASE DDJVUAPI_LIBS DDJVUAPI_CFLAGS NSDEJAVU_CFLAGS NSDEJAVU_LIBS INSTALL_SHLIB XDG_MIME XDG_ICON_RESOURCE XDG_DESKTOP_MENU LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -24546,6 +24546,166 @@ fi
 
 
 # ----------------------------------------
+# XDG tools
+# ----------------------------------------
+
+# Extract the first word of "xdg-mime", so it can be a program name with args.
+set dummy xdg-mime; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_XDG_MIME+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $XDG_MIME in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_XDG_MIME="$XDG_MIME" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_XDG_MIME="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+XDG_MIME=$ac_cv_path_XDG_MIME
+
+if test -n "$XDG_MIME"; then
+  echo "$as_me:$LINENO: result: $XDG_MIME" >&5
+echo "${ECHO_T}$XDG_MIME" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+# Extract the first word of "xdg-icon-resource", so it can be a program name with args.
+set dummy xdg-icon-resource; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_XDG_ICON_RESOURCE+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $XDG_ICON_RESOURCE in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_XDG_ICON_RESOURCE="$XDG_ICON_RESOURCE" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_XDG_ICON_RESOURCE="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+XDG_ICON_RESOURCE=$ac_cv_path_XDG_ICON_RESOURCE
+
+if test -n "$XDG_ICON_RESOURCE"; then
+  echo "$as_me:$LINENO: result: $XDG_ICON_RESOURCE" >&5
+echo "${ECHO_T}$XDG_ICON_RESOURCE" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+# Extract the first word of "xdg-desktop-menu", so it can be a program name with args.
+set dummy xdg-desktop-menu; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_XDG_DESKTOP_MENU+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $XDG_DESKTOP_MENU in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_XDG_DESKTOP_MENU="$XDG_DESKTOP_MENU" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_XDG_DESKTOP_MENU="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+XDG_DESKTOP_MENU=$ac_cv_path_XDG_DESKTOP_MENU
+
+if test -n "$XDG_DESKTOP_MENU"; then
+  echo "$as_me:$LINENO: result: $XDG_DESKTOP_MENU" >&5
+echo "${ECHO_T}$XDG_DESKTOP_MENU" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if test -x ${XDG_MIME} && \
+   test -x ${XDG_ICON_RESOURCE} && \
+   test -x ${XDG_DESKTOP_MENU}
+then
+  true
+elif test $ac_desktopfiles != no ; then
+  ac_desktopfiles = no
+  { echo "$as_me:$LINENO: WARNING: Cannot find the Xdg Portland tools.
+--------------------------------------------------------
+*** The Xdg Portland tools <http://portland.freedesktop.org>.
+*** are required to register the menu entries.
+*** You can install these tools later and then run the script
+*** ${datadir}/djvu/djview4/desktop/register-djview-menu.
+--------------------------------------------------------" >&5
+echo "$as_me: WARNING: Cannot find the Xdg Portland tools.
+--------------------------------------------------------
+*** The Xdg Portland tools <http://portland.freedesktop.org>.
+*** are required to register the menu entries.
+*** You can install these tools later and then run the script
+*** ${datadir}/djvu/djview4/desktop/register-djview-menu.
+--------------------------------------------------------" >&2;}
+else
+  { echo "$as_me:$LINENO: WARNING: Cannot find the Xdg Portland tools.
+--------------------------------------------------------
+*** You will not be able to use the script
+*** ${datadir}/djvu/djview4/desktop/register-djview-menu.
+*** without first installing the Xdg Portland tools
+*** available at <http://portland.freedesktop.org>.
+--------------------------------------------------------" >&5
+echo "$as_me: WARNING: Cannot find the Xdg Portland tools.
+--------------------------------------------------------
+*** You will not be able to use the script
+*** ${datadir}/djvu/djview4/desktop/register-djview-menu.
+*** without first installing the Xdg Portland tools
+*** available at <http://portland.freedesktop.org>.
+--------------------------------------------------------" >&2;}
+fi
+
+
+# ----------------------------------------
 # Paths
 # ----------------------------------------
 
@@ -25363,6 +25523,9 @@ s,@DDJVUAPI_CFLAGS@,$DDJVUAPI_CFLAGS,;t t
 s,@NSDEJAVU_CFLAGS@,$NSDEJAVU_CFLAGS,;t t
 s,@NSDEJAVU_LIBS@,$NSDEJAVU_LIBS,;t t
 s,@INSTALL_SHLIB@,$INSTALL_SHLIB,;t t
+s,@XDG_MIME@,$XDG_MIME,;t t
+s,@XDG_ICON_RESOURCE@,$XDG_ICON_RESOURCE,;t t
+s,@XDG_DESKTOP_MENU@,$XDG_DESKTOP_MENU,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
