record QMAKESPEC in config.status

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -843,13 +843,14 @@ X_CFLAGS
 X_PRE_LIBS
 X_LIBS
 X_EXTRA_LIBS
-QTDIR
 QMAKE
+QMAKESPEC
 MOC
 UIC
 RCC
 LUPDATE
 LRELEASE
+QTDIR
 DDJVUAPI_LIBS
 DDJVUAPI_CFLAGS
 TIFF_LIBS
@@ -891,13 +892,14 @@ CXXCPP
 PKG_CONFIG
 PKG_CONFIG_PATH
 XMKMF
-QTDIR
 QMAKE
+QMAKESPEC
 MOC
 UIC
 RCC
 LUPDATE
 LRELEASE
+QTDIR
 DDJVUAPI_LIBS
 DDJVUAPI_CFLAGS
 TIFF_LIBS
@@ -1521,13 +1523,14 @@ Some influential environment variables:
   PKG_CONFIG_PATH
               Path for pkg-config descriptors.
   XMKMF       Path to xmkmf, Makefile generator for X Window System
-  QTDIR       Location of the Qt package.
-  QMAKE       Location of the MOC program.
+  QMAKE       Location of the QMAKE program.
+  QMAKESPEC   Location of the QMAKE specifications.
   MOC         Location of the MOC program.
   UIC         Location of the UIC program.
   RCC         Location of the RCC program.
   LUPDATE     Location of the LUPDATE program.
   LRELEASE    Location of the LRELEASE program.
+  QTDIR       Location of the Qt package (deprecated).
   DDJVUAPI_LIBS
               Libraries for ddjvuapi
   DDJVUAPI_CFLAGS
@@ -6953,7 +6956,18 @@ fi
 
 
 
+
   path=$PATH
+  if test -n "QTDIR" && test -d "$QTDIR/include" ; then
+    if test -d "$QTDIR/include/Qt" ; then :
+    elif test -f "$QTDIR/include/qobject.h" ; then
+      unset QTDIR
+      { echo "$as_me:$LINENO: WARNING: We want Qt4 but your QTDIR variable points to a Qt3 install.
+Ignoring QTDIR and continuing with the search for Qt4." >&5
+echo "$as_me: WARNING: We want Qt4 but your QTDIR variable points to a Qt3 install.
+Ignoring QTDIR and continuing with the search for Qt4." >&2;}
+    fi
+  fi
   if test -n "$QTDIR" && test -d "$QTDIR/bin" ; then
     path=$QTDIR/bin:$PATH
   fi
@@ -7005,10 +7019,12 @@ done
 
   fi
   if test -z "$QMAKE" ; then
-    { { echo "$as_me:$LINENO: error: Cannot find Qt4 program qmake.
-Please define variable QMAKE or QTDIR." >&5
-echo "$as_me: error: Cannot find Qt4 program qmake.
-Please define variable QMAKE or QTDIR." >&2;}
+    { { echo "$as_me:$LINENO: error: Cannot find the Qt4 program qmake.
+Please define variable QMAKE and possibly QMAKESPEC.
+Defining QTDIR can help although it is deprecated." >&5
+echo "$as_me: error: Cannot find the Qt4 program qmake.
+Please define variable QMAKE and possibly QMAKESPEC.
+Defining QTDIR can help although it is deprecated." >&2;}
    { (exit 1); exit 1; }; }
   fi
   mkdir conftest.d
@@ -7019,8 +7035,6 @@ message(QT_VERSION="$$[QT_VERSION]")
 message(QT_INSTALL_PREFIX="$$[QT_INSTALL_PREFIX]")
 message(QT_INSTALL_DATA="$$[QT_INSTALL_DATA]")
 message(QT_INSTALL_BINS="$$[QT_INSTALL_BINS]")
-message(QMAKE_RUN_CC="$$QMAKE_RUN_CC")
-message(QMAKE_RUN_CXX="$$QMAKE_RUN_CXX")
 EOF
   if ( cd conftest.d && $QMAKE > conftest.out 2>&1 ) ; then
     sed -e 's/^.*: *//' < conftest.d/conftest.out > conftest.d/conftest.sh
@@ -7029,9 +7043,11 @@ EOF
   else
     rm -rf conftest.d
     { { echo "$as_me:$LINENO: error: Cannot successfully run Qt4 program qmake.
-Please define variable QMAKE to a working qmake." >&5
+Please define variable QMAKE to a working qmake.
+If you define QMAKESPEC, make sure it is correct." >&5
 echo "$as_me: error: Cannot successfully run Qt4 program qmake.
-Please define variable QMAKE to a working qmake." >&2;}
+Please define variable QMAKE to a working qmake.
+If you define QMAKESPEC, make sure it is correct." >&2;}
    { (exit 1); exit 1; }; }
   fi
   case "$QT_VERSION" in
@@ -7055,19 +7071,19 @@ Please define variable QMAKE to a suitable qmake." >&2;}
 echo "${ECHO_T}Defining QTDIR=$QTDIR" >&6; }
   fi
   path=$PATH
+  if test -n "$QTDIR" && test -d "$QTDIR/bin" ; then
+    path=$QTDIR/bin:$path
+  fi
   if test -d "$QT_INSTALL_BINS" ; then
     path=$QT_INSTALL_BINS:$path
   fi
-  if test -n "$QTDIR" && test -d "$QTDIR/bin" ; then
-    path=$QTDIR/bin:$PATH
-  fi
   if test -z "$MOC" ; then
-    if test -d "$QTDIR" && test -d "$QTDIR/bin" && test -x "$QTDIR/bin/moc" ; then
-      MOC="$QTDIR/bin/moc"
+    if test -x "$QMAKE_MOC" ; then
+      MOC=$QMAKE_MOC
       { echo "$as_me:$LINENO: result: Defining MOC=$MOC" >&5
 echo "${ECHO_T}Defining MOC=$MOC" >&6; }
-    elif test -x "$QMAKE_MOC" ; then
-      MOC=$QMAKE_MOC
+    elif test -d "$QTDIR" && test -d "$QTDIR/bin" && test -x "$QTDIR/bin/moc" ; then
+      MOC="$QTDIR/bin/moc"
       { echo "$as_me:$LINENO: result: Defining MOC=$MOC" >&5
 echo "${ECHO_T}Defining MOC=$MOC" >&6; }
     else
@@ -7077,12 +7093,12 @@ do
 set dummy $ac_prog; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_UIC+set}" = set; then
+if test "${ac_cv_path_MOC+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  case $UIC in
+  case $MOC in
   [\\/]* | ?:[\\/]*)
-  ac_cv_path_UIC="$UIC" # Let the user override the test with a path.
+  ac_cv_path_MOC="$MOC" # Let the user override the test with a path.
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
@@ -7092,7 +7108,7 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_UIC="$as_dir/$ac_word$ac_exec_ext"
+    ac_cv_path_MOC="$as_dir/$ac_word$ac_exec_ext"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -7103,28 +7119,28 @@ IFS=$as_save_IFS
   ;;
 esac
 fi
-UIC=$ac_cv_path_UIC
-if test -n "$UIC"; then
-  { echo "$as_me:$LINENO: result: $UIC" >&5
-echo "${ECHO_T}$UIC" >&6; }
+MOC=$ac_cv_path_MOC
+if test -n "$MOC"; then
+  { echo "$as_me:$LINENO: result: $MOC" >&5
+echo "${ECHO_T}$MOC" >&6; }
 else
   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
 fi
 
 
-  test -n "$UIC" && break
+  test -n "$MOC" && break
 done
 
     fi
   fi
   if test -z "$UIC" ; then
-    if test -d "$QTDIR" && test -d "$QTDIR/bin" && test -x "$QTDIR/bin/uic" ; then
-      UIC="$QTDIR/bin/uic"
+    if test -x "$QMAKE_UIC" ; then
+      UIC=$QMAKE_UIC
       { echo "$as_me:$LINENO: result: Defining UIC=$UIC" >&5
 echo "${ECHO_T}Defining UIC=$UIC" >&6; }
-    elif test -x "$QMAKE_UIC" ; then
-      UIC=$QMAKE_UIC
+    elif test -d "$QTDIR" && test -d "$QTDIR/bin" && test -x "$QTDIR/bin/uic" ; then
+      UIC="$QTDIR/bin/uic"
       { echo "$as_me:$LINENO: result: Defining UIC=$UIC" >&5
 echo "${ECHO_T}Defining UIC=$UIC" >&6; }
     else
@@ -7176,7 +7192,7 @@ done
     fi
   fi
   if test -z "$RCC" ; then
-    for ac_prog in rcc
+    for ac_prog in rcc-qt4 rcc
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -7223,7 +7239,7 @@ done
 
   fi
   if test -z "$LUPDATE" ; then
-    for ac_prog in lupdate
+    for ac_prog in lupdate-qt4 lupdate
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -7270,7 +7286,7 @@ done
 
   fi
   if test -z "$LRELEASE" ; then
-    for ac_prog in lrelease
+    for ac_prog in lrelease-qt4 lrelease
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -7316,6 +7332,7 @@ fi
 done
 
   fi
+  PATH=$path
 
 
 
@@ -9609,7 +9626,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 9612 "configure"' > conftest.$ac_ext
+  echo '#line 9629 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -11638,11 +11655,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11641: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11658: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11645: \$? = $ac_status" >&5
+   echo "$as_me:11662: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11900,11 +11917,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11903: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11920: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11907: \$? = $ac_status" >&5
+   echo "$as_me:11924: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11962,11 +11979,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11965: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11982: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11969: \$? = $ac_status" >&5
+   echo "$as_me:11986: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14186,7 +14203,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 14189 "configure"
+#line 14206 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14284,7 +14301,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 14287 "configure"
+#line 14304 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -16539,11 +16556,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16542: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16559: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16546: \$? = $ac_status" >&5
+   echo "$as_me:16563: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16601,11 +16618,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16604: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16621: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16608: \$? = $ac_status" >&5
+   echo "$as_me:16625: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17960,7 +17977,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17963 "configure"
+#line 17980 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18058,7 +18075,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18061 "configure"
+#line 18078 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18943,11 +18960,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18946: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18963: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18950: \$? = $ac_status" >&5
+   echo "$as_me:18967: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -19005,11 +19022,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19008: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19025: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:19012: \$? = $ac_status" >&5
+   echo "$as_me:19029: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21147,11 +21164,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:21150: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:21167: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:21154: \$? = $ac_status" >&5
+   echo "$as_me:21171: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -21409,11 +21426,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:21412: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:21429: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:21416: \$? = $ac_status" >&5
+   echo "$as_me:21433: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -21471,11 +21488,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:21474: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:21491: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:21478: \$? = $ac_status" >&5
+   echo "$as_me:21495: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -23695,7 +23712,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 23698 "configure"
+#line 23715 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -23793,7 +23810,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 23796 "configure"
+#line 23813 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -25158,9 +25175,11 @@ QARG="$QARG QMAKE_LFLAGS+="'"'"$LDFLAGS"'"'
 QARG="$QARG QMAKE_CFLAGS+="'"'"$CFLAGS $AUTO_FLAGS"'"'
 QARG="$QARG QMAKE_CXXFLAGS+="'"'"$CXXFLAGS $AUTO_FLAGS"'"'
 
-# quoting QARG with
-#  QARG=`echo $QARG | sed -e 's/"/"'"'"'"'"'"'"/g'`
-# is now useless because we set QMAKE_COMMAND with read!
+# qmake environment variables
+QENV=
+if test -n "$QMAKESPEC" ; then
+    QENV="$QENV QMAKESPEC="'"'"$QMAKESPEC"'"'
+fi
 
 # run
 ac_config_commands="$ac_config_commands src"
@@ -25730,8 +25749,8 @@ cat >>$CONFIG_STATUS <<_ACEOF
 # INIT-COMMANDS
 #
 
-     read QMAKE_COMMAND <<QMAKE_COMMAND_EOF
-$QMAKE $QARG
+    read QMAKE_COMMAND <<QMAKE_COMMAND_EOF
+$QENV $QMAKE $QARG
 QMAKE_COMMAND_EOF
 
 
@@ -25884,13 +25903,14 @@ X_CFLAGS!$X_CFLAGS$ac_delim
 X_PRE_LIBS!$X_PRE_LIBS$ac_delim
 X_LIBS!$X_LIBS$ac_delim
 X_EXTRA_LIBS!$X_EXTRA_LIBS$ac_delim
-QTDIR!$QTDIR$ac_delim
 QMAKE!$QMAKE$ac_delim
+QMAKESPEC!$QMAKESPEC$ac_delim
 MOC!$MOC$ac_delim
 UIC!$UIC$ac_delim
 RCC!$RCC$ac_delim
 LUPDATE!$LUPDATE$ac_delim
 LRELEASE!$LRELEASE$ac_delim
+QTDIR!$QTDIR$ac_delim
 DDJVUAPI_LIBS!$DDJVUAPI_LIBS$ac_delim
 DDJVUAPI_CFLAGS!$DDJVUAPI_CFLAGS$ac_delim
 TIFF_LIBS!$TIFF_LIBS$ac_delim
@@ -25906,7 +25926,6 @@ ac_ct_F77!$ac_ct_F77$ac_delim
 LIBTOOL!$LIBTOOL$ac_delim
 NSDEJAVU_CFLAGS!$NSDEJAVU_CFLAGS$ac_delim
 NSDEJAVU_LIBS!$NSDEJAVU_LIBS$ac_delim
-INSTALL_SHLIB!$INSTALL_SHLIB$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -25948,6 +25967,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+INSTALL_SHLIB!$INSTALL_SHLIB$ac_delim
 NSDEJAVU_YES!$NSDEJAVU_YES$ac_delim
 NSDEJAVU_NO!$NSDEJAVU_NO$ac_delim
 XDG_MIME!$XDG_MIME$ac_delim
@@ -25959,7 +25979,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 9; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 10; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -26363,8 +26383,8 @@ echo "$as_me: executing $ac_file commands" >&6;}
 
   case $ac_file$ac_mode in
     "src":C)
-     echo "config.status: running $QMAKE_COMMAND."
-     ( cd src ; eval "$QMAKE_COMMAND" )
+    echo "config.status: running $QMAKE_COMMAND."
+    ( cd src ; eval "$QMAKE_COMMAND" )
  ;;
 
   esac
