configure script changed to detect glib and enable xembed.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -856,6 +856,8 @@ DDJVUAPI_LIBS
 DDJVUAPI_CFLAGS
 TIFF_LIBS
 TIFF_CFLAGS
+GLIB_LIBS
+GLIB_CFLAGS
 ECHO
 AR
 RANLIB
@@ -905,6 +907,8 @@ DDJVUAPI_LIBS
 DDJVUAPI_CFLAGS
 TIFF_LIBS
 TIFF_CFLAGS
+GLIB_LIBS
+GLIB_CFLAGS
 CPP
 F77
 FFLAGS'
@@ -1538,6 +1542,8 @@ Some influential environment variables:
               Compilation flags for ddjvuapi
   TIFF_LIBS   Libraries for tiff
   TIFF_CFLAGS Compilation flags for tiff
+  GLIB_LIBS   Libraries for glib-2.0
+  GLIB_CFLAGS Compilation flags for glib-2.0
   CPP         C preprocessor
   F77         Fortran 77 compiler command
   FFLAGS      Fortran 77 compiler flags
@@ -7532,8 +7538,6 @@ echo "${ECHO_T}setting TIFF_LIBS=$TIFF_LIBS" >&6; }
    fi
 
 
-
-
 # ----------------------------------------
 # nsdejavu
 # ----------------------------------------
@@ -8865,9 +8869,45 @@ fi
         { echo "$as_me:$LINENO: WARNING: Disabling plugin compilation (missing X11 include files)." >&5
 echo "$as_me: WARNING: Disabling plugin compilation (missing X11 include files)." >&2;}
     fi
-fi
 
-if test "$ac_nsdejavu" != no ; then
+    ac_xt=yes
+    ac_glib=yes
+
+
+
+
+  { echo "$as_me:$LINENO: checking for glib" >&5
+echo $ECHO_N "checking for glib... $ECHO_C" >&6; }
+  if test -x "$PKG_CONFIG" ; then
+    if $PKG_CONFIG glib-2.0 ; then
+       ac_glib=yes
+       { echo "$as_me:$LINENO: result: found" >&5
+echo "${ECHO_T}found" >&6; }
+       GLIB_LIBS=`$PKG_CONFIG --libs glib-2.0`
+       { echo "$as_me:$LINENO: result: setting GLIB_LIBS=$GLIB_LIBS" >&5
+echo "${ECHO_T}setting GLIB_LIBS=$GLIB_LIBS" >&6; }
+       GLIB_CFLAGS=`$PKG_CONFIG --cflags glib-2.0`
+       { echo "$as_me:$LINENO: result: setting GLIB_CFLAGS=$GLIB_CFLAGS" >&5
+echo "${ECHO_T}setting GLIB_CFLAGS=$GLIB_CFLAGS" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_GLIB 1
+_ACEOF
+
+       :
+    else
+       { echo "$as_me:$LINENO: result: not found by pkg-config" >&5
+echo "${ECHO_T}not found by pkg-config" >&6; }
+       ac_glib=no
+       ac_glib=no
+    fi
+  else
+    { echo "$as_me:$LINENO: result: no pkg-config" >&5
+echo "${ECHO_T}no pkg-config" >&6; }
+    ac_glib=no
+    ac_glib=no
+  fi
+
     savedCFLAGS="$CFLAGS"
     CFLAGS="$CFLAGS ${X_CFLAGS}"
     if test "${ac_cv_header_X11_Shell_h+set}" = set; then
@@ -8998,7 +9038,7 @@ fi
 if test $ac_cv_header_X11_Shell_h = yes; then
   :
 else
-  ac_nsdejavu=no
+  ac_xt=no
 fi
 
 
@@ -9130,14 +9170,28 @@ fi
 if test $ac_cv_header_X11_IntrinsicP_h = yes; then
   :
 else
-  ac_nsdejavu=no
+  ac_xt=no
 fi
 
 
     CFLAGS="$savedCFLAGS"
-    if test "$ac_nsdejavu" = no ; then
-        { echo "$as_me:$LINENO: WARNING: Disabling plugin compilation (missing Xt include files)." >&5
-echo "$as_me: WARNING: Disabling plugin compilation (missing Xt include files)." >&2;}
+    if test "$ac_xt" != no ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_XT 1
+_ACEOF
+
+        if test "$ac_glib" = no ; then
+            { echo "$as_me:$LINENO: WARNING: GLib not found. Compiling plugin without XEmbed." >&5
+echo "$as_me: WARNING: GLib not found. Compiling plugin without XEmbed." >&2;}
+        fi
+    else
+        { echo "$as_me:$LINENO: WARNING: Xt not found. Compiling plugin with XEmbed only." >&5
+echo "$as_me: WARNING: Xt not found. Compiling plugin with XEmbed only." >&2;}
+        if test "$ac_glib" = no ; then
+            { echo "$as_me:$LINENO: WARNING: Disabling plugin compilation (need Xt and/or Glib2.)" >&5
+echo "$as_me: WARNING: Disabling plugin compilation (need Xt and/or Glib2.)" >&2;}
+        fi
     fi
 fi
 
@@ -9670,7 +9724,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 9673 "configure"' > conftest.$ac_ext
+  echo '#line 9727 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -11699,11 +11753,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11702: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11756: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11706: \$? = $ac_status" >&5
+   echo "$as_me:11760: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11961,11 +12015,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11964: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12018: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11968: \$? = $ac_status" >&5
+   echo "$as_me:12022: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12023,11 +12077,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12026: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12080: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12030: \$? = $ac_status" >&5
+   echo "$as_me:12084: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14247,7 +14301,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 14250 "configure"
+#line 14304 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14345,7 +14399,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 14348 "configure"
+#line 14402 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -16600,11 +16654,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16603: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16657: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16607: \$? = $ac_status" >&5
+   echo "$as_me:16661: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16662,11 +16716,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16665: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16719: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16669: \$? = $ac_status" >&5
+   echo "$as_me:16723: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18021,7 +18075,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18024 "configure"
+#line 18078 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18119,7 +18173,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18122 "configure"
+#line 18176 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19004,11 +19058,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19007: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19061: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19011: \$? = $ac_status" >&5
+   echo "$as_me:19065: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -19066,11 +19120,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19069: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19123: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:19073: \$? = $ac_status" >&5
+   echo "$as_me:19127: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21208,11 +21262,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:21211: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:21265: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:21215: \$? = $ac_status" >&5
+   echo "$as_me:21269: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -21470,11 +21524,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:21473: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:21527: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:21477: \$? = $ac_status" >&5
+   echo "$as_me:21531: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -21532,11 +21586,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:21535: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:21589: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:21539: \$? = $ac_status" >&5
+   echo "$as_me:21593: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -23756,7 +23810,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 23759 "configure"
+#line 23813 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -23854,7 +23908,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 23857 "configure"
+#line 23911 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -25960,6 +26014,8 @@ DDJVUAPI_LIBS!$DDJVUAPI_LIBS$ac_delim
 DDJVUAPI_CFLAGS!$DDJVUAPI_CFLAGS$ac_delim
 TIFF_LIBS!$TIFF_LIBS$ac_delim
 TIFF_CFLAGS!$TIFF_CFLAGS$ac_delim
+GLIB_LIBS!$GLIB_LIBS$ac_delim
+GLIB_CFLAGS!$GLIB_CFLAGS$ac_delim
 ECHO!$ECHO$ac_delim
 AR!$AR$ac_delim
 RANLIB!$RANLIB$ac_delim
@@ -25968,8 +26024,6 @@ CPP!$CPP$ac_delim
 F77!$F77$ac_delim
 FFLAGS!$FFLAGS$ac_delim
 ac_ct_F77!$ac_ct_F77$ac_delim
-LIBTOOL!$LIBTOOL$ac_delim
-NSDEJAVU_CFLAGS!$NSDEJAVU_CFLAGS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -26011,6 +26065,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+LIBTOOL!$LIBTOOL$ac_delim
+NSDEJAVU_CFLAGS!$NSDEJAVU_CFLAGS$ac_delim
 NSDEJAVU_LIBS!$NSDEJAVU_LIBS$ac_delim
 INSTALL_SHLIB!$INSTALL_SHLIB$ac_delim
 NSDEJAVU_YES!$NSDEJAVU_YES$ac_delim
@@ -26024,7 +26080,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 11; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 13; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
